# ─────────────────────────────
# 📄 CronJob Definition
# ─────────────────────────────
# This CronJob runs a task every minute.

apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-demo
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-container
              image: busybox
              command: ["sh", "-c", "date"]
          restartPolicy: OnFailure
